function corner_plot(param1,param2,nbins,optx,opty,truex,truey)
	meanx=mean(param1);sigmax=std(param1)
	meany=mean(param2);sigmay=std(param2)

	fig=figure(figsize=(8,8))
	subplots_adjust(hspace=0.02,wspace=0.02)
	subplot(223)
	ax1=gca()
	# tick_params(axis="both",direction="in")
	ax1.tick_params(top="true",right="true")
	plt.hist2d(param1,param2,bins=nbins,cmin=1)
	plot(truex,truey,ms=6,mec="white",mfc="blue",marker="o")
	# ax1.set_ylabel(L"Mass of Earth [$M_{\oplus}$]")
	# ax1.set_xlabel(L"Mass of Venus [$M_{\oplus}$]")
	axis([minimum(param1),maximum(param1),minimum(param2),maximum(param2)])
	subplot(221,sharex=ax1)
	ax2=gca()
	ax2.xaxis.set_visible(false)
	ax2.yaxis.set_visible(false)
	plt.hist(param1,bins=nbins,histtype="step",density="true",color="green") 
	axvline(optx,linestyle="--",color="black")
	axvline(meanx-sigmax,color="black")
	axvline(meanx+sigmax,color="black")
	subplot(224,sharey=ax1)
	ax3=gca()
	ax3.xaxis.set_visible(false)
	ax3.yaxis.set_visible(false)
	plt.hist(param2,bins=nbins,histtype="step",density="true",color="green",orientation="horizontal")
	axhline(opty,linestyle="--",color="black")
	axhline(meany-sigmay,color="black")
	axhline(meany+sigmay,color="black")
end